export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const FETCH_PICKUP = 'FETCH_PICKUP';
export const IS_PICKUP = 'IS_PICKUP';
export const PO_ADDED = 'PO_ADDED';
export const KANTOR_FETCHED = 'KANTOR_FETCHED';
export const ASSIGMENT_FETCHED = 'ASSIGMENT_FETCHED';
export const ASSIGMENT_ADDED = 'ASSIGMENT_ADDED';
export const GET_HANDOVER = 'GET_HANDOVER';
export const PETUGAS_FETCHED = 'PETUGAS_FETCHED';
export const LIMIT_FETCHED = 'LIMIT_FETCHED';
export const GET_ID_PO = 'GET_ID_PO';
export const FETCH_PO = 'FETCH_PO';
export const ADD_PO = 'ADD_PO'; // i mean add top up
export const FETCH_LIST_PO = 'FETCH_LIST_PO';
export const SET_PROGRESS_BAR = 'SET_PROGRESS_BAR';
export const FETCH_INVOICE = 'FETCH_INVOICE';